version: '3.8'

services:
  app:
    image: php:8.2-apache
    container_name: ci4-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:10.5
    container_name: ci4-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4db
    ports:
      - "3306:3306"